### ISSUE TITLE
Implement updated login page design

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/maap-auth-cas#3]
I have a new login page design that needs to be implemented in the CAS codebase.

![image](https://user-images.githubusercontent.com/931107/137013832-5f94186e-007f-4f1f-bdc6-28765107463f.png)

With your guidance @bsatoriu I can take a stab at implementing the design.

**Comment by anilnatha** [comment]
Reviewed the updates with George yesterday. The following updates/tasks need to be incorporated:

- [x] Add context messaging.
- [x] Add command to save a local copy of the generated WAR file from the tomcat-cas service.
- [x] Update Docker configuration to use docker-compose.

**Comment by anilnatha** [comment]
Deploying to DIT was successful; however, deploying to UAT uncovered an issue when login providers other than URS and ESA are present.

Brian and I discussed potential fixes which I will test out so we can try again.

**Comment by anilnatha** [comment]
Patches have been applied to remedy the issue we ran into in UAT during the first deployment. Updated code has been deployed to DIT and UAT and is ready for QA.

@oddes

**Comment by oddes** [comment]
looks good.
